// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpfVU_soBL6bW9Th0NCEmWjbSBYrHGDn0',
    appId: '1:650559505459:web:01feabe75f5baa2f65cf46',
    messagingSenderId: '650559505459',
    projectId: 'flutter-weimi-test',
    authDomain: 'flutter-weimi-test.firebaseapp.com',
    storageBucket: 'flutter-weimi-test.appspot.com',
    measurementId: 'G-6RR8ZLR9BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsREWyCcJbLeoLtKrOKFHesv8cthHHjuk',
    appId: '1:650559505459:android:bbcba9ca591862da65cf46',
    messagingSenderId: '650559505459',
    projectId: 'flutter-weimi-test',
    storageBucket: 'flutter-weimi-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsG1tOcEfDqfBleUe694CkGcnoM0wXBgc',
    appId: '1:650559505459:ios:27dbffb40cc46a6265cf46',
    messagingSenderId: '650559505459',
    projectId: 'flutter-weimi-test',
    storageBucket: 'flutter-weimi-test.appspot.com',
    iosBundleId: 'com.weiminet.flutterFcmTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsG1tOcEfDqfBleUe694CkGcnoM0wXBgc',
    appId: '1:650559505459:ios:27dbffb40cc46a6265cf46',
    messagingSenderId: '650559505459',
    projectId: 'flutter-weimi-test',
    storageBucket: 'flutter-weimi-test.appspot.com',
    iosBundleId: 'com.weiminet.flutterFcmTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpfVU_soBL6bW9Th0NCEmWjbSBYrHGDn0',
    appId: '1:650559505459:web:da6c0d8998dc525d65cf46',
    messagingSenderId: '650559505459',
    projectId: 'flutter-weimi-test',
    authDomain: 'flutter-weimi-test.firebaseapp.com',
    storageBucket: 'flutter-weimi-test.appspot.com',
    measurementId: 'G-8ZKBBBXDSZ',
  );

}